services:
  postgres:
    image: 'pgvector/pgvector:pg17'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=ds'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11435/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  ollama_data:
  postgres_data:
    driver: local
